---
title: "OLS"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
library(mgcv)
library(stargazer)
library(sf)
library(colorspace)
library("scales")

df_raw = read_csv(here("data", "NO2_ZEV_ZCTAs.csv"))
df = df_raw %>% select(-ZCTA, -n2_2019)

```

## Table 1: Summary Statistics

Create a LaTeX version of the data frame:

```{r}
tbl = stargazer(as.data.frame(df), nobs = F, 
                covariate.labels=c("Change in NO2, 2013-2019 (ppb)",
                                   "\\% ZEV, 2019",
                                   "\\% ZEV, 2013",
                                   "Population",
                                   "Median age",
                                   "\\% College educated",
                                   "\\% High school educated",
                                   "\\% White",
                                   "Median income",
                                   "\\% in poverty",
                                   "\\% of homes owner-occupied",
                                   "Median home value",
                                   "\\% Take automobile to work",
                                   "\\% Take public transit to work",
                                   "\\% Work from home",
                                   "Industrial employment density",
                                   "Road density",
                                   "Transit frequency (peak)",
                                   "Walkability index"
                ))
```

## Figure 1: Map of Treatment and Outcome

```{r}
# Read in shape data
df_shp = st_read(here("data", "NO2_ZEV_ZCTAs.shp"))
```

### NO2

```{r}
p = ggplot(df_shp) + geom_sf(aes(geometry=geometry, fill = no2), color = NA) + 
  theme(axis.line=element_blank(), 
        axis.text.x=element_blank(), axis.title.x=element_blank(),
        axis.text.y=element_blank(), axis.title.y=element_blank(),
        axis.ticks=element_blank(), 
        panel.background = element_blank()) + 
  scale_fill_gradientn(
      name = "Change in NO2, \n2013-2019 (ppb)",
      colors=c("darkblue","#f5f5f5","darkred"),
      values=rescale(c(-3.1,0,1.1)),
      limits=c(-3.1,1.1), oob = scales::squish
    )
ggsave(here("results", "CA-NO2.png"), plot = p, width = 5, height = 5, units = "in", dpi = 300)
p

```

### ZEV

```{r}

p = ggplot(df_shp) + geom_sf(aes(geometry=geometry, fill = ZEV_2019), color = NA) + 
  theme(axis.line=element_blank(), 
        axis.text.x=element_blank(), axis.title.x=element_blank(),
        axis.text.y=element_blank(), axis.title.y=element_blank(),
        axis.ticks=element_blank(), 
        panel.background = element_blank()) + 
  scale_fill_gradientn(
    name = "% of ZEV, 2019",
    colors=c("#f5f5f5","limegreen", "darkgreen"),
    values=rescale(c(0,5,21)),
    limits=c(0,21), oob = scales::squish, 
  )

ggsave(here("results", "CA-ZEV.png"), plot = p, width = 5, height = 5, units = "in", dpi = 300)
p
```

## Figure 2: Full Confounder Comparison

```{r}
estimate_df = read_csv(here("results", "mtp_analysis.csv"))
estimate_df$method = factor(estimate_df$method, c("NetworkMTP", "MTP",  "OLS"))
group.colors <- c("OLS" = "#7BA573", "MTP" = "#7BA573", "NetworkMTP" = "#000332")


p = ggplot(estimate_df) + 
  geom_vline(xintercept = 0, color = "darkgray") +
  geom_errorbarh(aes(y = method, xmin = lower, xmax = upper, color = method), 
                 height = .4, linewidth = 0.6) + 
  geom_point(aes(x = effects, y = method, color = method), size = 2.5) +
  theme_minimal() + 
  theme(axis.text.x = element_text(margin = margin(t = 4, r = 10, b = 10, l = 10)),
        legend.position = "none", 
        plot.margin = margin(, 2, , , "cm")
) +
  ylab("") + xlab("Change in NO2 (ppb)") +
  scale_color_manual(values=group.colors) 

p
ggsave(here("results", "data-MTP-comparison.png"))

```

## Figure 3: MTP Grid

```{r}
grid_df = read_csv(here("results", "mtp_grid.csv"))
grid_df$upper[1] = NA
grid_df$lower[1] = NA
grid_df = abs(grid_df)

p = ggplot(grid_df) + 
  geom_errorbar(aes(x = shift, ymin = lower, ymax = upper), 
                 width = 0, linewidth = 0.75, color = "#000332") + 
  geom_line(aes(x = shift, y = est), size = 0.75, color = "#000332") +
  xlab("Increase in Proportion of ZEVs Across CA (Percentage Point)") +
  ylab("Change in NO2 (ppb)") + 
  theme_minimal()

p

ggsave(here("results", "data-MTP-grid.png"))


```

## Table 2: Sensitivity Analysis
